packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  "@scarf/scarf": true
  "@swc/core": true
  "@tarojs/binding": true
  "@tarojs/cli": false
  core-js: true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  prisma: true

autoInstallPeers: false
engineStrict: true
injectWorkspacePackages: true
strictPeerDependencies: true

overrides:
  "@jimp/jpeg@0.6.8>jpeg-js": "0.4.4"
  "mkdirp@0.5.1>minimist": "1.2.8"

peerDependencyRules:
  ignoreMissing:
    - react
    - react-dom
